"""empty message

Revision ID: e83915999c1b
Revises: 46a262d3b9d5
Create Date: 2020-02-08 15:07:51.696866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83915999c1b'
down_revision = '46a262d3b9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vocab_id', sa.Integer(), nullable=True),
    sa.Column('n_seen', sa.Float(), nullable=True),
    sa.Column('n_test', sa.Float(), nullable=True),
    sa.Column('n_correct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('user')
    # ### end Alembic commands ###
